ThoroughWorks.Web/Controllers/DashboardController.cs
using MvcPaging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThoroughWorks.Data;
using ThoroughWorks.Repository.CardManagement;
using ThoroughWorks.Repository.SubscriberManagement;
using ThoroughWorks.Repository.HorseManagement;
using ThoroughWorks.Repository.UserManagement;
using ThoroughWorks.Repository.UserSaleLocationManagement;
using ThoroughWorks.Repository.ViewLogHistoryManagement;
using ThoroughWorks.Models;
using ThoroughWorks.Web.Models.Helpers;
using ThoroughWorks.Repository.VetWorkManagement;

namespace ThoroughWorks.Web.Controllers
{
  [Authorize]
  public class DashboardController : Controller
  {
    //
    // GET: /Dashboard/
    public ActionResult Index()
    {
      var model = new DashboardStatistics();

      //static counting set
      if (Helpers.isSuperAdmin())
      {
        // get super admin stats
        model.AdminSubscribers = SelectSubscriber.SelectAllSubscriber().Count; ;
        model.Horses = SelectHorses.SelectHorseCountForAllSubscribers();
      }
      else
      {
        var subscriber = SessionHelper.SubscriptionID;
        model.Horses = SelectHorses.SelectAllActiveHorse(subscriber, false).Count;
        model.SalesLocation = SelectUserSaleLocation.SelectAllUserSaleLocation(subscriber).ToList().Count;

        model.CurrentSaleLocations = SelectUserSaleLocation.SelectUserSalesLocationForDashboard(subscriber);
      }

      if (Helpers.isVet())
      {
          VetWorkSearch vwsearch = new VetWorkSearch();
          ViewBag.VetWorkSearch = vwsearch;
          vwsearch.Dt = DateTime.Now.Date;
          List<VetWork> list = null;
          if (Helpers.isAdmin())
              list = SelectVetWork.SelectAllVetWorkByDay(vwsearch.Dt);
          else
              list = SelectVetWork.SelectAllVetWorkByVetByDay(SessionHelper.UserID, vwsearch.Dt);

          model.VetWork = list.Select(vw => new VetWork_M
                                          {
                                              VetWorkID = vw.VetWorkID,
                                              HorseID = vw.HorseID,
                                              HorseName = vw.Horse.Name,
                                              VetID = vw.UserDetail.UserID,
                                              VetName = vw.UserDetail.FirstName + " " + vw.UserDetail.LastName,
                                              AgeCategory = vw.Horse.AgeCategory,
                                              VisitDate = vw.VisitDate,
                                              LastVisitDate = SelectVetWork.GetLastVisitDate(vw.HorseID, vw.VisitDate),
                                              NextVisitDate = SelectVetWork.SelectNextVisitDate(vw.HorseID, vw.VisitDate),
                                              NextInFor = SelectVetWork.SelectNextVisitDetails(vw.HorseID, vw.VisitDate).InFor,
                                              NextVisitID = SelectVetWork.SelectNextVisitDetails(vw.HorseID, vw.VisitDate).VetWorkID,
                                              InFor = vw.InFor,
                                              WorkCompleted = vw.WorkCompleted,
                                              Status = vw.Status
                                          }).OrderBy(vw => vw.VisitDate).ToList();
      }

      return View(model);
    }



    //public ActionResult VetWork(int? Page)
    //{
    //    int VetID = SessionHelper.UserID;
    //    int currentPageIndex = Page.HasValue ? Page.Value - 1 : 0;

    //    List<VetWork> vwl;
    //    vwl = SelectVetWork.SelectAllVetWorkByVetByDay(VetID, DateTime.Now.Date);


    //    List<VetWork_M> vetworkmodel = (from vw in vwl
    //                                    select new VetWork_M
    //                                    {
    //                                        VetWorkID = vw.VetWorkID,
    //                                        HorseID = vw.HorseID,
    //                                        HorseName = vw.Horse.Name,
    //                                        VetID = vw.UserDetail.UserID,
    //                                        VetName = vw.UserDetail.FirstName + " " + vw.UserDetail.LastName,
    //                                        AgeCategory = vw.AgeCategory,
    //                                        VisitDate = vw.VisitDate,
    //                                        LastVisitDate = SelectVetWork.GetLastVisitDate(vw.HorseID, vw.VisitDate),
    //                                        NextVisitDate = SelectVetWork.SelectNextVisitDate(vw.HorseID, vw.VisitDate),
    //                                        NextInFor = SelectVetWork.SelectNextVisitDetails(vw.HorseID, vw.VisitDate).InFor,
    //                                        NextVisitID = SelectVetWork.SelectNextVisitDetails(vw.HorseID, vw.VisitDate).VetWorkID,
    //                                        InFor = vw.InFor,
    //                                        WorkCompleted = vw.WorkCompleted,
    //                                        Status = vw.Status

    //                                    }).OrderBy(vw => vw.VisitDate).ToList();


    //    IPagedList<VetWork_M> vwpagedlist = vetworkmodel.ToPagedList(currentPageIndex, 10);
    //    return PartialView("VetWorkListing", vwpagedlist);
    //}

    [HttpGet]
    public ActionResult DeleteVetWorkRecord(int VetWorkID, int VetID)
    {

        DeleteVetWork deletevw = new DeleteVetWork();
        deletevw.Do(VetWorkID);


        return RedirectToAction("Index");

    }


    //#region "Supporing method"

    //private void SetUserHorseSale()
    //{
    //    SelectUserSaleLocation selectuserlocation = new SelectUserSaleLocation();
    //    List<UserSaleLocation> lst = selectuserlocation.SelectAllUserSaleLocation(SessionHelper.SubscriptionID);

    //    List<UserSaleLocation_M> locationmodel = (from aa in lst
    //                                              select new UserSaleLocation_M
    //                                              {
    //                                                  Active = aa.Active,
    //                                                  CreatedBy = aa.CreatedBy,
    //                                                  CreatedDate = aa.CreatedDate,
    //                                                  EndDate = aa.EndDate,
    //                                                  SaleName = aa.SaleName,
    //                                                  Location = aa.Location,
    //                                                  StartDate = aa.StartDate,
    //                                                  UpdatedBy = aa.UpdatedBy,
    //                                                  UpdatedDate = aa.UpdatedDate,
    //                                                  UserID = aa.UserID,
    //                                                  UserSaleLocationID = aa.UserSaleLocationID,
    //                                                  UserName = aa.UserDetail != null ? aa.UserDetail.UserName : "",
    //                                                  horses = (from hors in aa.UserHorseSales
    //                                                            select new UserHorseSale_M
    //                                                            {
    //                                                                HorseID = hors.HorseID,
    //                                                                Sequence = hors.Sequence,
    //                                                                UserHorseSaleID = hors.UserHorseSaleID,
    //                                                                UserSaleLocationID = hors.UserSaleLocationID
    //                                                            }).ToList()
    //                                              }).ToList();

    //    ViewBag.horsesales = locationmodel;
    //}

    //#endregion
  }
}

ThoroughWorks.Web/Views/VetWork/AddEdit.cshtml
@using ThoroughWorks.Models
@using ThoroughWorks.Web.Models.Helpers
@model VetWork_M

@{
    ViewBag.Title = "Vet Work Management";
    ViewBag.PageTitle = "Vet Work Management";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@section Breadcrumbs
{
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Dashboard")">Home</a>
        </li>
        <li>
            <a href="@Url.Action("Index", "VetWork")">Vet Work</a>
        </li>
        <li class="active">
            <i class="fa fa-user"></i>
            @if (Model.VetWorkID == 0)
            {
                @Html.Raw("Add New Appointment")
            }
            else
            {
                @Html.Raw("Edit Appointment")
            }
        </li>
    </ul>
}

<div class="col-lg-6 col-md-6 col-sm-8 col-xs-24 no-margin no-padding">
    <div class="widget">
        <div class="widget-header bg-blue">
            @if (Model.VetWorkID == 0)
            {
                <span class="widget-caption">New Appointment</span>
            }
            else
            {
                <span class="widget-caption">Edit Appointment</span>
            }

        </div>
        <div class="widget-body">
            @using (Html.BeginForm("SaveRecord", "VetWork", FormMethod.Post, new { @class = "form-horizontal", @style = "clear:none", @enctype = "multipart/form-data" }))
            {
                <input type="hidden" id="ReturnUrl" name="ReturnUrl" value="@ViewBag.ReturnUrl" />
                @Html.EditorForModel()

                <button type="submit" class="btn btn-success">Save Changes</button>
                if (Model.VetWorkID != 0)
                {
                    <a href="@Url.Action("Complete","VetWork", new { id = Model.VetWorkID})" class="btn btn-primary">Complete</a>
                }
                <a href="@ViewBag.ReturnUrl" class="btn btn-warning">Cancel</a>
            }
        </div>
    </div>
</div>



@section Scripts
{
   
    
    <script type="text/javascript">
        jQuery.validator.defaults.ignore = ".ignore";
        //$.validator.unobtrusive.parse("#AddEditForm");
        jQuery(function ($) {
            $.validator.addMethod('date',
            function (value, element) {
                if (this.optional(element)) {
                    return true;
                }

                var ok = true;
                try {
                    $.datepicker.parseDate('dd/mm/yyyy', value);
                }
                catch (err) {
                    ok = false;
                }
                return ok;
            });
        });
        initPlugins();

        $("#HorseID").select2();

    </script>

    
}

ThoroughWorks.Web/Views/VetWork/Complete.cshtml
@using ThoroughWorks.Models
@using ThoroughWorks.Web.Models.Helpers
@model VetWork_M

@{
    ViewBag.Title = "Vet Work Management";
    ViewBag.PageTitle = "Vet Work Management";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@section Breadcrumbs
{
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Dashboard")">Home</a>
        </li>
        <li>
            <a href="@Url.Action("Index", "VetWork")">Vet Work</a>
        </li>
        <li class="active">
            <i class="fa fa-user"></i>

            @Html.Raw("Complete Appointment")

        </li>
    </ul>
}

<div class="col-lg-6 col-md-6 col-sm-8 col-xs-24 no-margin no-padding">

    <form class="form-horizontal" style="clear: none" method="post"  id="CompleteForm">
        <input type="hidden" id="ReturnUrl" name="ReturnUrl" value="@ViewBag.ReturnUrl" />
                        @Html.HiddenFor(model => model.HorseID)
                        @Html.HiddenFor(model => model.HorseName)
                        @Html.HiddenFor(model => model.VetWorkID)
                        @Html.HiddenFor(model => model.NextVisitID)
                        @Html.HiddenFor(model => model.VetName)
                        @Html.HiddenFor(model => model.VisitDate, new { @class = "ignore" })

        <div class="widget">
            <div class="widget-header bg-blue">

                <span class="widget-caption">Appointment Details</span>

            </div>
            <div class="widget-body">


                <div class="form-group">
                    <label class="col-lg-3 col-sm-3" for="Name">@Html.DisplayNameFor(m => m.HorseName) </label>
                    <div class="col-lg-9 col-sm-9">
                        @Html.DisplayFor(model => model.HorseName)
                    </div>
                </div>


                <div class="form-group">
                    <label class="col-lg-3 col-sm-3" for="Name">@Html.DisplayNameFor(m => m.VetName) </label>
                    <div class="col-lg-9 col-sm-9">
                        @Html.DisplayFor(model => model.VetName)

                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-24">
                        @Html.HiddenFor(model => model.VetID)
                    </div>
                </div>


                <div class="form-group">
                    <label class="col-lg-3 col-sm-3" for="Name">@Html.DisplayNameFor(m => m.AgeCategory) </label>
                    <div class="col-lg-9 col-sm-9">
                        @Html.DisplayFor(model => model.AgeCategoryDisplay)
                        @Html.HiddenFor(model => model.AgeCategory)
                    </div>

                </div>

                <div class="form-group">
                    <label class="col-lg-3 col-sm-3" for="Name">@Html.DisplayNameFor(m => m.VisitDate)</label>
                    <div class="col-lg-9 col-sm-9">
                        @String.Format("{0:dd/MM/yyyy}", Model.VisitDate)
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-24">
                        @Html.ValidationMessageFor(model => model.VisitDate)
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-3 col-sm-3" for="Name">@Html.DisplayNameFor(m => m.InFor)</label>
                    <div class="col-lg-9 col-sm-9">
                        @Html.DisplayFor(model => model.InFor)
                        @Html.HiddenFor(model => model.InFor)
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-3 col-sm-3" for="Name">@Html.DisplayNameFor(m => m.Status)</label>
                    <div class="col-lg-9 col-sm-9">
                        @Html.DisplayFor(model => model.Status)
                        @Html.HiddenFor(model => model.Status)

                    </div>
                </div>
            </div>
        </div>

        <div class="widget">
            <div class="widget-header bg-blue">
                <span class="widget-caption">Complete Appointment</span>
            </div>
            <div class="widget-body">

                @Html.EditorForModel()

                <button type="submit" class="btn btn-success">Save Changes</button>
                <a href="@Url.Action("Index")" class="btn btn-warning">Cancel</a>

            </div>
        </div>
    </form>
</div>



@section Scripts
{
    <script type="text/javascript">
        jQuery.validator.defaults.ignore = ".ignore";
        $.validator.unobtrusive.parse("#CompleteForm");
        jQuery(function ($) {
            $.validator.addMethod('date',
            function (value, element) {
                if (this.optional(element)) {
                    return true;
                }

                var ok = true;
                try {
                    $.datepicker.parseDate('dd/mm/yyyy', value);
                }
                catch (err) {
                    ok = false;
                }
                return ok;
            });
        });
        initPlugins();




    </script>
}

ThoroughWorks.Web/Views/VetWork/Index.cshtml
@model ThoroughWorks.Models.VetWorkSearch

@{
    ViewBag.Title = "Vet Work Management";
    ViewBag.PageTitle = "Vet Work Management";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Breadcrumbs
{
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Dashboard")">Home</a>
        </li>
        <li class="active">
            <i class="fa fa-stethoscope"></i>
            Vet Work
        </li>
    </ul>
}

<div class="well">
    <form id="formConfig" name="formConfig">

        <div class="row">
            <div class="col-lg-3 col-sm-3 col-xs-3">
                <a class="btn btn-blue" href="@Url.Action("Add", "VetWork")">Add a New Appointment</a>
            </div>
        </div>
    </form>
</div>


<div id='calendar'>
</div>


@section Scripts
{
    <script src="~/Content/beyond-admin/js/fullcalendar/fullcalendar.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            // init calendar...

            $('#calendar').fullCalendar({
                // put your options and callbacks here
                timeFormat: 0,
                events: '/VetWork/GetVetWorkCalendarEvents',
                eventClick: function (calEvent, jsEvent, view) {
                    window.location = '/VetWork/WorkList/?VetID=' + calEvent.vetID + '&VisitDate=' + calEvent.startDateTime;
                },
                dayClick: function (date, allDay, jsEvent, view) {
                    var month = date.getMonth();
                    month += 1;
                    window.location = '/VetWork/WorkListD/?VetID=0&VisitDate=' + date.getDate() + '/' + month + '/' + date.getFullYear();
                }

            })
        }
    )
    </script>



}

ThoroughWorks.Web/Views/VetWork/Listing.cshtml
@using MvcPaging
@using ThoroughWorks.Models
@using ThoroughWorks.Web.Models.Helpers
@model IPagedList<VetWork_M>


<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th style="width: 15%;">Horse</th>
            <th style="width: 10%;" class="hidden-xs hidden-sm hidden-md">Age</th>
            <th style="width: 15%;" class="hidden-xs">Vet</th>
            <th style="width: 10%;" class="hidden-xs hidden-sm hidden-md">Last Visit</th>
            <th style="width: 10%;" class="hidden-xs hidden-sm">Visit Date</th>
            <th style="width: 20%;">In For</th>
            <th style="width: 10%;" class="hidden-xs hidden-sm">Status</th>
            <th style="width: 15%;"></th>
        </tr>
    </thead>
    <tbody>

        @Html.DisplayForModel()

    </tbody>
</table>
@if (Model.Count > 0)
{
    @Ajax.CustomAjaxPager(Model.PageSize, Model.PageNumber, Model.TotalItemCount, "AjaxList", null, new CustomAjax
    {
        FormToPost = "#formVetWork",
        UrlToPost = @Url.Action("AjaxListing"),
        UpdateType = UpdateType.replace,
        UpdateControl = "#listingData"
    })
}

ThoroughWorks.Web/Views/VetWork/ListingPDF.cshtml
@using MvcPaging
@using ThoroughWorks.Models
@using ThoroughWorks.Web.Models.Helpers
@model IPagedList<VetWork_M>


<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th style="width: 30%;">Horse</th>
            <th style="width: 20%;">Age</th>
            <th style="width: 15%;">Vet</th>
            <th style="width: 10%;">Last Visit</th>
            <th style="width: 10%;">Visit Date</th>
            <th style="width: 20%;">In For</th>
            <th style="width: 10%;">Status</th>
        </tr>
    </thead>
    <tbody>

        

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.HorseName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AgeCategoryDisplay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VetName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastVisitDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VisitDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InFor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
    </tr>
}



    </tbody>
</table>

ThoroughWorks.Web/Views/VetWork/WorkList.cshtml
@model MvcPaging.IPagedList<ThoroughWorks.Models.VetWork_M>
@using ThoroughWorks.Web.Models.Helpers
@using ThoroughWorks.Models
@{
    ViewBag.Title = "Vet Work";
    //ViewBag.PageTitle = "Vet Work";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Breadcrumbs
{
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Dashboard")">Home</a>
        </li>
        <li class="active">
            <i class="fa fa-stethoscope"></i>
            <a href="@Url.Action("Index", "VetWork")">Vet Work</a>
        </li>
        <li class="active">
            <i class="fa fa-clipboard"></i>
            Work List
        </li>
    </ul>
}


@{
    int VetID = (ViewBag.Search as VetWorkSearch ?? new VetWorkSearch()).VetID;
    string Dt = (ViewBag.Search as VetWorkSearch ?? new VetWorkSearch()).Dt.ToString("dd/MM/yyyy");
}


<div class="well">
    <form id="formConfig" name="formConfig">

        <div class="row">
            <div class="col-lg-12">
                <a class="btn btn-blue" href="@Url.Action("Add", "VetWork")">Add a New Appointment</a>
@if( Model.Count > 0 )
{
                <a class="btn btn-blue" href="@Url.Action("WorkSheet", "VetWork", new { VetID = VetID, VisitDate = Dt, ReturnUrl = Server.UrlEncode(Request.Url.ToString()) })">Work Sheet</a>
                <a class="btn btn-blue" href="@Url.Action("WorkSheetToPDF", "VetWork")" target="_blank">Print Work Sheet</a>
}    
            </div>
        </div>
    </form>
</div>

<div class="clear"></div>

<form id="formVetWork" name="formVetWork">
<input type="hidden" id="Page" name="page" value="@Model.PageNumber"/>    
</form>

<div id="listingData">
    @{Html.RenderPartial("Listing", Model);}
</div>





<script type="text/javascript">

    function Reloadables() {
        $(".remove-vetwork").on("click", function () {
            var url = '@Url.Action("AjaxListing")';
            var vetWorkID = $(this).closest("tr").find(".vetwork-id").val();
            if (confirm('Are you sure you want to delete this appointment?')) {
                showloading();
                var page = $("#Page").val();
                $.ajax({
                    url: '@Url.Action("DeleteRecord")',
                    data: {
                        VetWorkID: vetWorkID,
                        Page: page
                    },
                    context: document.body,
                    success: function (data) {
                        $(".alert").attr("class", "alert alert-success");
                        $(".message-text").html("Appointment Removed Successfully");
                        $(".fa-fw").attr("class", "fa-fw fa fa-check");
                        $(".alert").show();
                        setMessageTimeout();

                        $.post(url, $('#formConfig').serialize(), function (data, status) {
                            $('#listingData').html(data);
                            hideloading();
                            Reloadables();
                        });

                    },
                    error: function (err) {
                        hideloading();
                        alert(err);
                    }
                });
            }
        });

        $("#formConfig").on("submit", function () {
            var url = '@Url.Action("AjaxListing")';
            $('#Page').val('1');
            $.post(url, $('#formConfig').serialize(), function (data, status) {
                $('#listingData').html(data);
                Reloadables();
            });
            return false;
        });
    }
    $(document).ready(function () {
        Reloadables();
    });

</script>

ThoroughWorks.Web/Views/VetWork/WorkListPDF.cshtml
@model MvcPaging.IPagedList<ThoroughWorks.Models.VetWork_M>
@using ThoroughWorks.Web.Models.Helpers
@using ThoroughWorks.Models
@{
    //ViewBag.Title = "Vet Appointments " + ViewBag.DisplayDate;    
    Layout = "~/Views/Shared/_ReportLayout.cshtml";
}


    <div id="listingData">
        @{Html.RenderPartial("ListingPDF");}
    </div>





    

ThoroughWorks.Web/Views/VetWork/WorkSheet.cshtml
@using ThoroughWorks.Web.Models.Helpers
@using ThoroughWorks.Models
@model List<ThoroughWorks.Models.VetWork_M>


@{
    ViewBag.Title = "Vet Work";
    //ViewBag.PageTitle = "Vet Work";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.RenderSidebar = false;

}

@section Breadcrumbs
{
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Dashboard")">Home</a>
        </li>
        <li class="active">
            <i class="fa fa-stethoscope"></i>
            <a href="@Url.Action("Index", "VetWork")">Vet Work</a>
        </li>
        <li class="active">
            <i class="fa fa-clipboard"></i>
            Work Sheet
        </li>
    </ul>
}


@{
    int VetID = (ViewBag.Search as VetWorkSearch ?? new VetWorkSearch()).VetID;
    DateTime Dt = (ViewBag.Search as VetWorkSearch ?? new VetWorkSearch()).Dt;
}





<form method="post">
    @*@using (Html.BeginForm("WorkSheet", "VetWork", FormMethod.Post, new { @class = "form-horizontal", @style = "clear:none", @enctype = "multipart/form-data" }))
{
    *@<input type="hidden" id="ReturnUrl" name="ReturnUrl" value="@ViewBag.ReturnUrl" />

    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th style="width: 10%;">Horse</th>
                <th style="width: 10%;">In For</th>
                @if (Model.Count > 0)
                {
                    VetWork_M item = Model.First();
                    {
                        List<VetWorkCompleted_M> vcl = item.VetWorkCompleted;
                        if (vcl != null && vcl.Count > 0)
                        {
                            foreach (VetWorkCompleted_M vc in vcl)
                            {
        
                    <th>
                        @Html.DisplayFor(m => vc.VetWorkAttributeName)

                    </th>
                            }
                        }

                    }
                }

                <th style="width: 15%;">Comments</th>
                <th style="width: 10%;">Next In Date and For</th>

            </tr>
        </thead>
        <tbody>


            @for (var i = 0; i < Model.Count; i++)
            {
                @Html.EditorFor(m => Model[i], "VetWork_Worksheet")
            }
        </tbody>
    </table>

    <div class="well">
        <input type="submit" class="btn btn-success" value="Save Work Sheet" />
        <a class="btn btn-blue" href="@Url.Action("WorkSheetToPDF", "VetWork")" target="_blank">Print Work Sheet</a>
        <a class="btn btn-warning" href="@ViewBag.ReturnUrl">Close</a>
    </div>

</form>





@section Scripts
{
    <script type="text/javascript">
        jQuery.validator.defaults.ignore = ".ignore";
        $.validator.unobtrusive.parse("#AddEditForm");
        jQuery(function ($) {
            $.validator.addMethod('date',
            function (value, element) {
                if (this.optional(element)) {
                    return true;
                }

                var ok = true;
                try {
                    console.log(value);
                    $.datepicker.parseDate('dd/MM/yyyy', value);
                }
                catch (err) {
                    console.error("dateerr");
                    ok = false;
                }
                return ok;
            });
        });
        initPlugins();

        $('.autogrow').autosize();


    </script>
}

ThoroughWorks.Web/Views/VetWork/WorkSheetPDF.cshtml
@using ThoroughWorks.Web.Models.Helpers
@using ThoroughWorks.Models
@model List<ThoroughWorks.Models.VetWork_M>

@{
    Layout = "~/Views/Shared/_ReportLayout.cshtml";
}

@{
    int VetID = (ViewBag.Search as VetWorkSearch ?? new VetWorkSearch()).VetID;
    DateTime Dt = (ViewBag.Search as VetWorkSearch ?? new VetWorkSearch()).Dt;
}

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th style="width: 10%;">Horse</th>
            @if (VetID == 0)
            {
            <th style="width: 10%;">Vet</th>
            }
            <th style="width: 10%;">In For</th>
            @if (Model.Count > 0)
            {
                VetWork_M item = Model.First();
                {
                    List<VetWorkCompleted_M> vcl = item.VetWorkCompleted;
                    if (vcl != null && vcl.Count > 0)
                    {
                        var basewidth = 50;
                        if (VetID == 0)
                        {
                            basewidth = 40;
                        }
                        var width = Math.Floor(basewidth / (decimal)vcl.Count);
                        foreach (VetWorkCompleted_M vc in vcl)
                        {
        
                <th style="width:@width.ToString()%;">
                    @Html.DisplayFor(m => vc.VetWorkAttributeName)

                </th>
                        }
                    }

                }
            }

            <th style="width: 15%;">Comments</th>
            <th style="width: 15%;">Next Visit (Date + In for)</th>

        </tr>
    </thead>
    <tbody>


        @for (var i = 0; i < Model.Count; i++)
        {
            @Html.DisplayFor(m => Model[i], "VetWork_WorksheetPDF", new { VetID = VetID })
        }
    </tbody>
</table>