ThoroughWorks.Web/Controllers/ImageGalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace ThoroughWorks.Web.Controllers
{
    public class ImageGalleryController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult LightBoxPartial()
        {
            return PartialView();
        }
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public FileResult GetImageFile(string imagePath)
        {
            return File(Server.MapPath(imagePath), "image/jpeg");
        }
	}
}

ThoroughWorks.Web/Controllers/OwnerController.cs
using MvcPaging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Routing;
using ThoroughWorks.Data;
using ThoroughWorks.Models;
using ThoroughWorks.Web.Models.Helpers;
using ThoroughWorks.Repository.OwnerManagement;

namespace ThoroughWorks.Web.Controllers
{
    [Authorize]
    public class OwnerController : Controller
    {
        #region "get methods"

        public ActionResult Index()
        {
            OwnerSearch ownersearch = (OwnerSearch)TempData["ownersearch"];
            ownersearch = ownersearch ?? new OwnerSearch();
            ViewBag.Search = ownersearch;
            IPagedList<Owner_M> ownerPaged = SelectOwnerFilterBased(ownersearch);
            return View(ownerPaged);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return PartialView("AddEdit", new Owner_M() { SubscriberID = SessionHelper.SubscriptionID });
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Owner owner = SelectOwners.SelectOwnerByID(id);

            Owner_M owner_m = new Owner_M()
            {
                OwnerID = owner.OwnerID,
                Name = owner.Name,
                EmailAddress = owner.EmailAddress,
                ContactNumber = owner.ContactNumber,
                Active = owner.Active,
                SubscriberID = owner.SubscriberID,
                OwnedHorses = owner.HorseOwners.Select(h => new Horse_M
                {
                    Active = h.Horse.Active,
                    Colour = h.Horse.Colour,
                    Comments = h.Horse.Comments,
                    Dam = h.Horse.Dam,
                    DateArrived = h.Horse.DateArrived,
                    DateSold = h.Horse.DateSold,
                    DOB = h.Horse.DOB,
                    HorseID = h.Horse.HorseID,
                    Name = h.Horse.Name,
                    Sex = h.Horse.Sex,
                    SireID = (int) h.Horse.SireID,
                    SireDisplay = h.Horse.Sire.SireName,
                    SubscriberID = h.Horse.SubscriberID,
                }).ToList(),
            };
            return View("AddEdit", owner_m);
        }

        [HttpGet]
        public ActionResult DeleteRecord(int ownerID)
        {
            DeleteOwner deleteowner = new DeleteOwner();
            deleteowner.Do(ownerID);

            IPagedList<Owner_M> ownersPaged = SelectOwnerFilterBased(new OwnerSearch());
            return PartialView("Listing", ownersPaged);
        }

        private IPagedList<Owner_M> SelectOwnerFilterBased(OwnerSearch search)
        {
            int currentPageIndex = search.Page.HasValue ? search.Page.Value - 1 : 0;
            List<Owner> owners = (from o in SelectOwners.SelectAllActiveOwners(SessionHelper.SubscriptionID)
                                  where ((String.IsNullOrWhiteSpace(search.SearchName) || Helpers.ConvertString(o.Name).ToLower().Contains(search.SearchName.ToLower())))
                                  select o).ToList();

            List<Owner_M> ownermodel = (from aa in owners
                                        select new Owner_M
                                            {
                                                OwnerID = aa.OwnerID,
                                                Name = aa.Name,
                                                EmailAddress = aa.EmailAddress,
                                                ContactNumber = aa.ContactNumber,
                                                Active = aa.Active,
                                                SubscriberID = aa.SubscriberID,
                                            }).ToList();
            IPagedList<Owner_M> ownerpage = ownermodel.OrderBy(j => j.OwnerID).ToPagedList(currentPageIndex, 10);
            return ownerpage;
        }

        #endregion

        #region "Post methods"

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult SaveRecord(Owner_M owner_m, OwnerSearch search)
        {
            if (ModelState.IsValid) //if valid model then update the record and show list
            {
                Owner owner = new Owner()
                {
                    OwnerID = owner_m.OwnerID,
                    Name = owner_m.Name,
                    EmailAddress = owner_m.EmailAddress,
                    ContactNumber = owner_m.ContactNumber,
                    Active = owner_m.Active,
                    SubscriberID = owner_m.SubscriberID
                };

                if (owner.OwnerID == 0)
                {
                    CreateOwner createowner = new CreateOwner();
                    createowner.Do(owner);
                }
                else
                {
                    UpdateOwner updateowner = new UpdateOwner();
                    updateowner.Do(owner);
                }

                IPagedList<Owner_M> ownerPaged = SelectOwnerFilterBased(search);

                TempData["ownersearch"] = search;
                return RedirectToAction("Index");
            }
            this.Response.StatusCode = 400;
            return PartialView("AddEdit", owner_m);
        }

        [HttpPost]
        public ActionResult AjaxListing(OwnerSearch search)
        {
            IPagedList<Owner_M> ownerPaged = SelectOwnerFilterBased(search);
            return PartialView("Listing", ownerPaged);
        }

        [HttpPost]
        public ActionResult Validate(Owner_M owner_m)
        {
            bool valid = true;
            if (ModelState.IsValid)
            {
                valid = true;
                return Json(valid, JsonRequestBehavior.AllowGet);
            }
            else
            {
                this.Response.StatusCode = 400;
                return PartialView("AddEdit", owner_m);
            }
        }

        #endregion
    }
}

ThoroughWorks.Web/Controllers/SaleCardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcPaging;
using ThoroughWorks.Data;
using ThoroughWorks.Repository.UserSaleLocationManagement;
using ThoroughWorks.Repository.UserHorseSaleManagement;
using ThoroughWorks.Models;
using ThoroughWorks.Web.Models.Helpers;
using ThoroughWorks.Repository.HorseManagement;
using ThoroughWorks.Repository.ViewLogHistoryManagement;
using ThoroughWorks.Repository.CardManagement;
using ThoroughWorks.Repository.OwnerManagement;
using ThoroughWorks.Repository.UserManagement;
using Postal;
using System.Net.Mail;
using CommunicationsManager;
using System.Configuration;
using ThoroughWorks.Repository.SubscriberManagement;

namespace ThoroughWorks.Web.Controllers
{
    [Authorize]
    public class SaleCardController : Controller
    {
        #region "Get Methods"
        public ActionResult Index(int id, string DateFrom = "", string DateTo = "", string ReturnUrl = "")
        {
            DateTime? fromDate;
            DateTime? toDate;

            // Set start date
            if (!String.IsNullOrEmpty(DateFrom))
            {
                fromDate = DateTime.Parse(DateFrom);
            }
            else
            {
                var sale = SelectUserSaleLocation.SelectUserSaleLocationByID(id);
                if (DateTime.Today >= sale.StartDate && DateTime.Today <= sale.EndDate)
                {
                    fromDate = DateTime.Today;
                }
                else
                {
                    fromDate = DateTime.MinValue;
                }
            }

            // set end date
            if (!String.IsNullOrEmpty(DateTo))
            {
                toDate = DateTime.Parse(DateTo);
            }
            else
            {
                var sale = SelectUserSaleLocation.SelectUserSaleLocationByID(id);
                if (DateTime.Today >= sale.StartDate && DateTime.Today <= sale.EndDate)
                {
                    toDate = sale.EndDate.HasValue ? sale.EndDate.Value : DateTime.MaxValue.AddDays(-1);
                }
                else
                {
                    toDate = DateTime.MaxValue.AddDays(-1);
                }
            }

            //IPagedList<SaleCard> lst = FilterRecord(new SaleCardSearch());
            List<Card> lst = SelectCard.SelectCardByLocation(id, fromDate.Value, toDate.Value.AddDays(1).AddTicks(-1));
            List<Card_M> cardm = (from card in lst
                                  select new Card_M
                                  {
                                      CardID = card.CardID,
                                      PersonName = card.PersonName,
                                      UserID = card.UserID,
                                      SubscriberID = card.SubscriberID,
                                      UserName = card.UserDetail.UserName,
                                      SaleName = card.UserSaleLocation.SaleName,
                                      UserRefNo = card.UserRefNo,
                                      UserSaleLocationID = card.UserSaleLocationID,
                                      CardUID = card.CardUID,
                                      InspectionDate= card.InspectionDate,
                                      Horses = (from hs in card.CardHorses
                                                select new Horse_M
                                                {
                                                    Active = hs.Horse.Active,
                                                    AttachmentsPath = hs.Horse.Attachments,
                                                    Comments = hs.Horse.Comments,
                                                    Dam = hs.Horse.Dam,
                                                    DateArrived = hs.Horse.DateArrived,
                                                    DateSold = hs.Horse.DateSold,
                                                    DOB = hs.Horse.DOB,
                                                    HorseID = hs.Horse.HorseID,
                                                    ImagePath = hs.Horse.Image,
                                                    Name = hs.Horse.Name,
                                                    Owners = hs.Horse.HorseOwners.Select(o => new HorseOwner_M()
                                                    {
                                                        HorseOwnerID = o.HorseOwnerID,
                                                        HorseID = o.HorseID,
                                                        Active = o.Owner.Active,
                                                        ContactNumber = o.Owner.ContactNumber,
                                                        EmailAddress = o.Owner.EmailAddress,
                                                        Name = o.Owner.Name,
                                                        OwnerID = o.Owner.OwnerID,
                                                        SubscriberID = o.Owner.SubscriberID,
                                                        Delete = false
                                                    }).ToList(),
                                                    SireID = (int) hs.Horse.SireID,
                                                    SireDisplay = hs.Horse.Sire.SireName,
                                                }).ToList()
                                  }).OrderByDescending(j => j.Horses.Count).OrderByDescending(j => j.PersonName).ToList();

            SetLocationName(id);

            ViewBag.FromDateField = fromDate.Value;
            ViewBag.ToDateField = toDate.Value;

            ViewBag.DateFrom = fromDate.Value.ToString("yyyyMMdd");
            ViewBag.DateTo = toDate.Value.ToString("yyyyMMdd");

            ViewBag.ReturnUrl = String.IsNullOrEmpty(ReturnUrl) ? Url.Action("Index", "Dashboard") : Server.UrlDecode(ReturnUrl);

            return View(cardm);
        }

        private void SetLocationName(int LocationID)
        {
            UserSaleLocation salelocation = SelectUserSaleLocation.SelectUserSaleLocationByID(LocationID);
            ViewBag.SearchUserSaleLocationID = LocationID;
            ViewBag.SaleLocationName = salelocation.SaleName;
            ViewBag.SaleLocationID = LocationID;
            ViewBag.SearchUserID = SessionHelper.UserID;
        }

        public ActionResult Add(int id, string ReturnUrl = "")
        {
            UserSaleLocation location = SelectUserSaleLocation.SelectUserSaleLocationByID_LazyLoading(id);
            SaleCard card = new SaleCard()
            {
                UserSaleLocationID = location.UserSaleLocationID,
                SaleName = location.SaleName,
                NumberSessions = location.NumberSessions,
                Active = true,
                SubscriberID = SessionHelper.SubscriptionID,
                UserID = SessionHelper.UserID,
                InspectionDate = DateTime.Now.Date,
                Horses = (from aa in location.UserHorseSales
                          select new SaleCardHorses
                          {
                              HorseImage = aa.Horse.Image,
                              HorseName = aa.Horse.Name,
                              HorseID = aa.Horse.HorseID,
                              Sequence = aa.Sequence,
                              DOB = aa.Horse.DOB,
                              Comment = aa.Horse.Comments,
                              AttachmentsPath = aa.Horse.Attachments,
                              Dam = aa.Horse.Dam,
                              Sire = aa.Horse.Sire.SireName,
                              Owners = aa.Horse.HorseOwners.Select(o => new HorseOwner_M()
                              {
                                  HorseOwnerID = o.HorseOwnerID,
                                  HorseID = o.HorseID,
                                  Active = o.Owner.Active,
                                  ContactNumber = o.Owner.ContactNumber,
                                  EmailAddress = o.Owner.EmailAddress,
                                  Name = o.Owner.Name,
                                  OwnerID = o.Owner.OwnerID,
                                  SubscriberID = o.Owner.SubscriberID,
                                  Delete = false
                              }).ToList(),
                              DateArrived = aa.Horse.DateArrived,
                              DateSold = aa.Horse.DateSold,
                              Sex = aa.Horse.Sex,
                              Colour = aa.Horse.Colour,
                              LotNumber = aa.LotNumber,
                              SessionNumber = aa.SessionNumber
                          }).OrderBy(j => j.LotNumber).ThenBy(j => j.Sequence).ToList()
            };
            ViewBag.ReturnUrl = String.IsNullOrEmpty(ReturnUrl) ? Url.Action("Index", "Dashboard") : Server.UrlDecode(ReturnUrl);
            return View("AddEdit", card);

        }

        public ActionResult ChooseSale(string ReturnUrlType = "", bool forceDisplaySales = false)
        {
            switch (ReturnUrlType.ToLower())
            {
                case "cards":
                    ViewBag.ReturnUrl = "/SaleCard/Index/{0}";
                    break;
                default:
                    ViewBag.ReturnUrl = "/Dashboard";
                    break;
            }

            //int currentPageIndex = search.page.HasValue ? search.page.Value - 1 : 0;
            List<UserSaleLocation> sales = (from slocation in SelectUserSaleLocation.SelectAllUserSaleLocation(SessionHelper.SubscriptionID)
                                            //where ((String.IsNullOrWhiteSpace(search.SearchName) || Helpers.ConvertString(slocation.SaleName).ToLower().Contains(Helpers.ConvertString(search.SearchName).ToLower())))

ThoroughWorks.Web/Views/SaleCard/DisplayTemplates/CardHorseViewerModel.cshtml
@using ThoroughWorks.Models;
@model CardHorseViewerModel

@{
    var preSale = Model.ViewList.Where(x => x.Date < ViewBag.SaleStartDate).Sum(x => x.Views);
    var total = Model.ViewList.Sum(x => x.Views);
    
}
<tr>
    <td>@Model.ViewerName</td>
    <td style="text-align: center;" class="hidden-xs">
        @if (preSale > 0)
        {
            @Html.Raw(preSale)
        }
    </td>
    @foreach (var date in (List<DateTime>)ViewBag.ViewDates)
    {
        var dayTotal = ((List<CardHorseViewerModel>)ViewBag.TotalList).Sum(x => x.ViewList.Where(z => z.Date == date).Sum(z => z.Views));
        var hidden = "";
        if (dayTotal == 0)
        {
            hidden = "hidden-sm hidden-md";
        }
        
        if (Model.ViewList.Any(x => x.Date == date))
        {
        <td style="text-align: center;" class="hidden-xs">@Model.ViewList.FirstOrDefault(x => x.Date == date).Views</td>
        }
        else
        {
        <td style="text-align: center;" class="hidden-xs @hidden"></td>
        }
    }

    <td style="text-align: center;">@total</td>
</tr>

ThoroughWorks.Web/Views/SaleCard/DisplayTemplates/Card_M.cshtml
@using ThoroughWorks.Web.Models.Helpers;
@model ThoroughWorks.Models.Card_M

<tr>
    <td>@Html.ActionLink(Model.CardUID, "Edit", "SaleCard", new { id = Model.CardID, ReturnUrl = Server.UrlEncode(Request.Url.ToString()) }, null)</td>
    <td>@Html.ActionLink(String.Format("{0:dd/MM/yyyy}",Model.InspectionDate), "Edit", "SaleCard", new { id = Model.CardID, ReturnUrl = Server.UrlEncode(Request.Url.ToString()) }, null)</td>
    <td>@Html.ActionLink(String.IsNullOrEmpty(Model.PersonName) ? "Name not provided" : Model.PersonName, "Edit", "SaleCard", new { id = Model.CardID, ReturnUrl = Server.UrlEncode(Request.Url.ToString()) }, null)</td>
    <td>@Html.Raw(String.Join("<br/>", (from aa in Model.Horses
                                        select aa.Name).ToArray()))

    </td>
    <td style="text-align: right;">
        <a href="@Url.Action("Edit", "SaleCard", new { id = Model.CardID, ReturnUrl = Server.UrlEncode(Request.Url.ToString()) })" class="edit-card btn btn-primary icon-button btn-sm  hidden-xs" title="Edit Inspection Card"><i class="fa fa-edit"></i></a>
        @if (Helpers.isAdmin())
        {
            @Html.HiddenFor(m => m.CardID, new { @class = "cardid" })
            @Html.HiddenFor(m => m.UserSaleLocationID, new { @class = "saleid" })
            <a href="javascript:void(0);" class="remove-card btn btn-danger  icon-button btn-sm" title="Remove Card"><i class="fa fa-times"></i></a>
        }

    </td>

</tr>

ThoroughWorks.Web/Views/SaleCard/DisplayTemplates/Owner_M.cshtml
@using ThoroughWorks.Web.Models.Helpers;
@using ThoroughWorks.Web.App_Code;
@model ThoroughWorks.Models.Owner_M

<tr>
  <td><div class="checkbox">@Html.CheckBoxFor(m => m.IsSelected)</div></td>
  <td>
    @Html.HiddenFor(m => m.OwnerID, new { @class = "owner-id" })
    @Html.HiddenFor(m => m.EmailAddress)
    @Html.HiddenFor(m => m.HorsesOnSale)
    @Html.HiddenFor(m => m.Name)
    @Html.ActionLink(Model.Name, "Edit", "Owner", new { id = Model.OwnerID }, null)
  </td>
  <td class="hidden-xs">
       @foreach (var horse in Model.HorsesOnSale)
      {
          @Html.Raw(horse.Name)<br />
      }
  <td>
      @Html.TextAreaFor(m => m.Message, new { @class="form-control", @style = "height:100%; min-height:60px;", value = "Testing" })
  </td>
</tr>

ThoroughWorks.Web/Views/SaleCard/DisplayTemplates/SaleCardHorses.cshtml
@model ThoroughWorks.Models.SaleCardHorses

@{
    var bgColor= "none";
if (Model.Selected)
{
    bgColor = "rgb(215, 255, 216)";
}
}
<tr class="row-click" style="background-color:@bgColor; cursor:pointer;">
    @*<td>@Html.CheckBoxFor(m => m.Selected, new { @class = "selected" })
    </td>*@
    <td>
        @Html.HiddenFor(m => m.Selected, new { @class = "selected" })
        @Html.DisplayFor(m => m.LotNumber)
        @Html.HiddenFor(m => m.LotNumber)
        @Html.HiddenFor(m => m.SessionNumber, new { @class = "sessionnumber" })
    </td>
    <td>@Html.DisplayFor(m => m.Colour)
        @Html.HiddenFor(m => m.Colour)
    </td>
    <td>@Html.DisplayFor(m => m.Sex)
        @Html.HiddenFor(m => m.Sex, new { @class = "sex" })
    </td>
    <td>@Html.DisplayFor(m => m.Sire)
        @Html.HiddenFor(m => m.Sire)
    </td>
    <td>@Html.DisplayFor(m => m.Dam)
        @Html.HiddenFor(m => m.Dam)
    </td>
    @*<td>@Html.DisplayFor(m => m.DOB)
        @Html.HiddenFor(m => m.DOB)
    </td>*@
    <td class="ignore-clicks">
        @Html.HiddenFor(m => m.Sequence)
        @Html.HiddenFor(m => m.AttachmentsPath)
        @if (!String.IsNullOrEmpty(Model.HorseImage))
        {
        @*<div class="thumbnail">*@
                <a href="@Url.Action("GetImageFile", "ImageGallery", new { imagePath = "~/files/" + Model.HorseID + "/" + Model.HorseImage })" data-lightbox="horseimage" title="@Model.HorseName">
                    @*@GeneralHelper.GetImage(Model.HorseImage, Model.HorseID)*@See Horse
                </a>
        @*</div>*@
        }
    </td>
    <td class="ignore-clicks">
        @if (!String.IsNullOrEmpty(Model.AttachmentsPath))
        {
            @GeneralHelper.GetAttachmentPath(Model.HorseID, Model.AttachmentsPath)
        }
                                    @*<span onclick="ToggleDetail(this,'@Model.HorseID','@ViewBag.SaleLocationID.');"><i class="icon-plus pointer" style="font-size: 24px;"></i></span>*@
        @Html.HiddenFor(m => m.HorseID)
        @Html.HiddenFor(m => m.HorseImage)
        @Html.HiddenFor(m => m.HorseName)
    </td>
</tr>

ThoroughWorks.Web/Views/SaleCard/DisplayTemplates/UserSaleLocation_M.cshtml
@model ThoroughWorks.Models.UserSaleLocation_M

<tr>
    <td>@Html.DisplayFor(m => m.SaleName)</td>
    <td class="hidden-xs">@Html.DisplayFor(m => m.Location)</td>
    <td class="hidden-xs hidden-sm">@Html.DisplayFor(m => m.StartDate)</td>
    <td class="hidden-xs hidden-sm">@Html.DisplayFor(m => m.EndDate)</td>
    <td>
        <a href="@String.Format(ViewBag.ReturnUrl, Model.UserSaleLocationID)" class="btn btn-blue"><i class="fa fa-check"></i>Select</a>
    </td>
</tr>