ThoroughWorks.Web/Controllers/UserManagementController.cs
using MvcPaging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThoroughWorks.Data;
using ThoroughWorks.Repository.UserManagement;
using ThoroughWorks.Models;
using ThoroughWorks.Web.Models.Helpers;

namespace ThoroughWorks.Web.Controllers
{
    [Authorize]
    public class UserManagementController : Controller
    {
        #region "get methods"

        public ActionResult Index()
        {

            IPagedList<UserDetail_M> userPaged = SelectUserFilterBased(new UserDetailSearch());
            return View(userPaged);
        }

        [HttpGet]
        public ActionResult Add(int? SubscriberID, string ReturnUrl = "")
        {
            var model = new UserDetail_M();
            if (SubscriberID.HasValue)
                model.SubscriberID = SubscriberID.Value;
            else
                model.SubscriberID = SessionHelper.SubscriptionID;

            model.SelectedRoles = new List<int>();
            if (SubscriberID == 0)
            { 
                // super admin
                model.SelectedRoles.Add(5);
            } 
            else
            {
                // normal user by default
                model.SelectedRoles.Add(2);
            }


            ViewBag.ReturnUrl = Url.Action("Index");
            if (!String.IsNullOrEmpty(ReturnUrl))
                ViewBag.ReturnUrl = Server.UrlDecode(ReturnUrl);
            return View("AddEdit", model);


        }

        [HttpGet]
        public ActionResult Edit(int UserID)
        {
            UserDetail userdetail = SelectUserDetails.SelectByUserID(UserID);

            UserDetail_M userdetail_m = new UserDetail_M()
            {
                UserID = userdetail.UserID,
                UserName = userdetail.UserName,
                EmailID = userdetail.EmailID,
                FirstName = userdetail.FirstName,
                Password = userdetail.Password,
                LastName = userdetail.LastName,
                PhoneNumber = userdetail.PhoneNumber,
                RoleMasterIDs = userdetail.UserRoles.Count > 0 ? (from bb in userdetail.UserRoles select Convert.ToString(bb.RoleMasterID)).ToArray() : new string[0],
                Active = true,
                SubscriberID = SessionHelper.SubscriptionID,
                EmailSignature = userdetail.EmailSignature
            };
            ViewBag.ReturnUrl = Url.Action("Index");
            return View("AddEdit", userdetail_m);
        }

        [HttpGet]
        public ActionResult DeleteRecord(int UserID)
        {
            DeleteUserDetails deleteuserDetail = new DeleteUserDetails();
            deleteuserDetail.Do(UserID);

            IPagedList<UserDetail_M> userPaged = SelectUserFilterBased(new UserDetailSearch());
            return PartialView("Listing", userPaged);
        }

        private IPagedList<UserDetail_M> SelectUserFilterBased(UserDetailSearch search)
        {
            int currentPageIndex = search.page.HasValue ? search.page.Value - 1 : 0;
            List<UserDetail> users = new List<UserDetail>();
            if (SessionHelper.SubscriptionID == 0)
            {
                users = (from usr in SelectUserDetails.SelectAdministrationUsers()
                         where ((String.IsNullOrWhiteSpace(search.SearchFirstName) || Helpers.ConvertString(usr.FirstName).ToLower().Contains(Helpers.ConvertString(search.SearchFirstName).ToLower()))
                         && (String.IsNullOrWhiteSpace(search.SearchLastName) || Helpers.ConvertString(usr.LastName).ToLower().Contains(Helpers.ConvertString(search.SearchLastName).ToLower())))
                         select usr).ToList();
            }
            else
            {
                users = (from usr in SelectUserDetails.SelectAllActiveUsers(SessionHelper.SubscriptionID)
                         where ((String.IsNullOrWhiteSpace(search.SearchFirstName) || Helpers.ConvertString(usr.FirstName).ToLower().Contains(Helpers.ConvertString(search.SearchFirstName).ToLower()))
                         && (String.IsNullOrWhiteSpace(search.SearchLastName) || Helpers.ConvertString(usr.LastName).ToLower().Contains(Helpers.ConvertString(search.SearchLastName).ToLower())))
                         select usr).ToList();
            }

            List<UserDetail_M> usermodel = (from aa in users
                                            select new UserDetail_M
                                            {
                                                Active = aa.Active,
                                                EmailID = aa.EmailID,
                                                FirstName = aa.FirstName,
                                                LastName = aa.LastName,
                                                Password = aa.Password,
                                                PhoneNumber = aa.PhoneNumber,
                                                RoleMasterIDs = aa.UserRoles.Count > 0 ? (from bb in aa.UserRoles select Convert.ToString(bb.RoleMasterID)).ToArray() : new string[0],
                                                RoleMasterName = aa.UserRoles.Count > 0 ? String.Join("<br />", (from bb in aa.UserRoles select Convert.ToString(bb.RoleMaster.RoleName)).ToArray()) : "",
                                                UserID = aa.UserID,
                                                UserName = aa.UserName,
                                                EmailSignature = aa.EmailSignature
                                            }).ToList();
            IPagedList<UserDetail_M> userPaged = usermodel.OrderBy(j => j.UserID).ToPagedList(currentPageIndex, 10);
            return userPaged;
        }
        #endregion

        #region "Post methods"
        [HttpPost]
        public ActionResult AjaxListing(UserDetailSearch search)
        {
            IPagedList<UserDetail_M> userPaged = SelectUserFilterBased(search);
            return PartialView("Listing", userPaged);
        }

        [HttpPost]
        public ActionResult Add(UserDetail_M userdetail_m, UserDetailSearch search, string ReturnUrl)
        {
            if (ModelState.IsValid) //if valid model then update the record and show list
            {
                try
                {
                    UserDetail userdetail = new UserDetail()
                    {
                        UserID = userdetail_m.UserID,
                        UserName = userdetail_m.UserName,
                        EmailID = userdetail_m.EmailID,
                        FirstName = userdetail_m.FirstName,
                        Password = userdetail_m.Password,
                        LastName = userdetail_m.LastName,
                        PhoneNumber = userdetail_m.PhoneNumber,
                        Active = true,
                        EmailSignature = userdetail_m.EmailSignature
                    };

                    //user roles
                    List<UserRole> userrole = new List<UserRole>();
                    if (userdetail_m.SelectedRoles != null)
                    {
                        foreach (int role in userdetail_m.SelectedRoles)
                        {
                            userrole.Add(new UserRole() { UserID = userdetail_m.UserID, RoleMasterID = role });
                        }
                    }
                    userdetail.UserRoles = userrole;

                    CreateUserDetails createuserdetail = new CreateUserDetails();
                    userdetail.CreatedBy = SessionHelper.UserID;
                    userdetail.CreatedDate = DateTime.Now;
                    createuserdetail.Do(userdetail, userdetail_m.SubscriberID);

                    Session["Message"] = "User Created Successfully";

                    if (!String.IsNullOrEmpty(ReturnUrl))
                        return Redirect(Server.UrlDecode(ReturnUrl));
                    else
                        return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.InnerException != null ? ex.InnerException.Message : ex.Message);
                }
            }

            ViewBag.ReturnUrl = Url.Action("Index");
            if (!String.IsNullOrEmpty(ReturnUrl))
                ViewBag.ReturnUrl = Server.UrlDecode(ReturnUrl);

            return View("AddEdit", userdetail_m);
        }

        [HttpPost]
        public ActionResult Edit(UserDetail_M userdetail_m, UserDetailSearch search, string ReturnUrl)
        {
            if (String.IsNullOrEmpty(userdetail_m.Password))
                // remove password field
                ModelState.Remove("PassworD");

            if (ModelState.IsValid) //if valid model then update the record and show list
            {
                try
                {

                    UserDetail userdetail = new UserDetail()
                    {
                        UserID = userdetail_m.UserID,
                        UserName = userdetail_m.UserName,
                        EmailID = userdetail_m.EmailID,
                        FirstName = userdetail_m.FirstName,
                        Password = userdetail_m.Password,
                        LastName = userdetail_m.LastName,
                        PhoneNumber = userdetail_m.PhoneNumber,
                        Active = true,
                        EmailSignature = userdetail_m.EmailSignature
                    };

                    //user roles
                    List<UserRole> userrole = new List<UserRole>();
                    if (userdetail_m.SelectedRoles != null)
                    {
                        foreach (int role in userdetail_m.SelectedRoles)
                        {
                            userrole.Add(new UserRole() { UserID = userdetail_m.UserID, RoleMasterID = role });
                        }
                    }
                    userdetail.UserRoles = userrole;

ThoroughWorks.Web/Views/UserManagement/AddEdit.cshtml
@using ThoroughWorks.Models
@using ThoroughWorks.Web.Models.Helpers
@model UserDetail_M

@{
    ViewBag.Title = (Model.UserID > 0) ? "Edit " + Model.FirstName + " " + Model.LastName : "Add New User";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.PageTitle = (Model.UserID > 0) ? "Edit User - " + Model.FirstName + " " + Model.LastName : "Add New User"; ;
    var userFullName = (Model.UserID > 0) ? Model.FirstName + " " + Model.LastName : "Add New User"; ;

    var passwordPlaceholder = "";
    if (Model.UserID > 0)
    {
        passwordPlaceholder = "To change the user's password please enter here.  Leave blank to keep existing password";
    }
    
}

@section Breadcrumbs
{
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Dashboard")">Home</a>
        </li>
        <li class="active">
            <i class="fa fa-user"></i>
            <a href="@Url.Action("Index", "UserManagement")">
                @if (SessionHelper.SubscriptionID == 0)
                {
                    @Html.Raw("Administrators")
                }
                else
                {
                    @Html.Raw("Users")
                }
            </a>
        </li>
        <li class="active">
            @userFullName
        </li>
    </ul>
}

<form class="well widget flat radius-bordered no-margin" role="form" method="post" id="formUser">
    <div>
        <div class="widget-header bg-blue">
            <span class="widget-caption">User Information</span>
        </div>
        <div class="widget-body">
            <div class="form-group">
                @Html.LabelFor(m => m.FirstName)
                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.LastName)
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.EmailID)
                @Html.TextBoxFor(m => m.EmailID, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber)
                @Html.TextBoxFor(model => model.PhoneNumber, null, new { maxlength = 20, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
        </div>
    </div>
    <div>
        <div class="widget-header bg-blue">
            <span class="widget-caption">Access Details</span>
        </div>
        <div class="widget-body">
            <div class="form-group">
                @Html.LabelFor(model => model.UserName)
                @Html.TextBoxFor(model => model.UserName, null, new { maxlength = 100, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserName)

                @Html.HiddenFor(model => model.UserID)
                @Html.HiddenFor(model => model.SubscriberID)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Password, new { @data_toggle = "tooltip", @data_placement = "right", data_original_title = passwordPlaceholder })
                @Html.PasswordFor(model => model.Password, new { @class = "ignore form-control", maxlength = 50 })
                @Html.ValidationMessageFor(model => model.Password)
            </div>
            <div class="form-group">
                <div>@Html.LabelFor(model => model.RoleMasterIDs)</div>
                @Html.ListBox("SelectedRoles", DropDownHelper.GetAllRoles(Model.RoleMasterIDs, Model.SubscriberID == 0), new { multiple = "multiple", @style = "width:100%;" })
            </div>
        </div>



        <div class="widget-header bg-blue">
            <span class="widget-caption">Email Signature</span>
        </div>
        <div class="widget flat radius-bordered">
                                
                <div class="widget-body">
                    <div class="widget-main no-padding">
                        <div id="summernote"></div>
                        @Html.HiddenFor(m => m.EmailSignature)
                    </div>
                </div>
            </div>


        


        <div class="widget-body">

            <div class="form-group">
                <button type="submit" class="btn btn-success">Submit</button>
                <a href="@ViewBag.ReturnUrl" class="btn btn-warning">Cancel</a>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    <script src="~/Scripts/bootstrap-multiselect.js"></script>
    <!--Page Related Scripts-->
    <!--Jquery Select2-->
    <script src="/content/beyond-admin/js/select2/select2.js"></script>
    <!--Bootstrap Tags Input-->
    <script src="/content/beyond-admin/js/tagsinput/bootstrap-tagsinput.js"></script>
    
    <!--Summernote Scripts-->
    <script src="/content/beyond-admin/js/editors/summernote/summernote.js"></script>
    <script>
        $('#summernote').summernote(
            {
                height: 300,
                onImageUpload: function (files, editor, welEditable) {
                    sendFile(files[0], editor, welEditable);

                }
            });

        function sendFile(file, editor, welEditable) {
            data = new FormData();
            data.append("file", file);
            $.ajax({
                data: data,
                type: "POST",
                url: "/UserManagement/SendSignatureImage",
                cache: false,
                contentType: false,
                processData: false,
                success: function (url) {
                    editor.insertImage(welEditable, url);
                }
            })
        };
    </script>



    <script type="text/javascript">
        $(document).ready(function () {
            var sig = $("#EmailSignature").val().replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
            $(".note-editable").html(sig);
            

            $("#formUser").on("submit", function () {
                $("#EmailSignature").val($(".note-editable").html().replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'));
            });

            // hide video, full screen, code view and help buttons on signature control
            $('button[data-original-title="Video"]').remove();
            $('button[data-original-title="Full Screen"]').remove();
            $('button[data-original-title="Code View"]').remove();
            $('button[data-original-title="Help"]').remove();

        });

        


        $("#SelectedRoles").select2({
            placeholder: "Select Roles",
            allowClear: true
        });

        jQuery.validator.defaults.ignore = ".ignore";

        $.validator.unobtrusive.parse("#AddEditForm");

        $('.multiselect').multiselect();


    </script>
}

ThoroughWorks.Web/Views/UserManagement/Index.cshtml
@using ThoroughWorks.Web.Models.Helpers;
@model MvcPaging.IPagedList<ThoroughWorks.Models.UserDetail_M>
@{
    ViewBag.Title = "User Management";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.PageTitle = "User Management";
}

@section Breadcrumbs
{
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Dashboard")">Home</a>
        </li>
        <li class="active">
            <i class="fa fa-user"></i>
            @if (SessionHelper.SubscriptionID == 0)
            {
                @Html.Raw("Administrators")
            }
            else
            {
                @Html.Raw("Users")
            }
        </li>
    </ul>

}


<div class="row">
    <div class="col-lg-4 col-sm-4 col-xs-8">
        <a class="btn btn-blue" href="@Url.Action("Add")">Add a New User</a>
    </div>
</div>
<div class="well">
    <form id="formConfig" name="formConfig">
        <h4>Search</h4>
        <input type="hidden" id="Page" name="page" />
        <div class="form-inline">
            <div class="form-group ">
                <div class="col-lg-12 no-padding">
                    <label class="sr-only" for="SearchFirstName">First Name</label>
                    @Html.TextBox("SearchFirstName", "", new { @class = "form-control", placeholder = "First Name" })
                </div>
            </div>
            <div class="form-group ">
                <div class="col-lg-12 no-padding">
                    <label class="sr-only" for="SearchLastName">Last Name</label>
                    @Html.TextBox("SearchLastName", "", new { @class = "form-control", placeholder = "Last Name" })
                </div>
            </div>
            <div class="form-group ">
                <div class="col-lg-12 no-padding">
                    <input type="submit" class="btn btn-blue" value="Search">
                </div>
            </div>
        </div>
    </form>
    <div class="clear"></div>
</div>
<div id="listingData">
    @{Html.RenderPartial("Listing", Model);}
</div>
@section Scripts
{
    <script src="~/Scripts/bootstrap-multiselect.js"></script>
    <script type="text/javascript">
        function Reloadables() {
           $(".remove-user").on("click", function () {
                var url = '@Url.Action("AjaxListing")';
                var userID = $(this).closest("tr").find(".user-id").val();
                if (confirm('Are you sure you want to delete this user?')) {
                    showloading();
                    $.ajax({
                        url: '@Url.Action("DeleteRecord")',
                        data: { UserID: userID },
                        context: document.body,
                        success: function (data) {
                            $(".alert").attr("class", "alert alert-success");
                            $(".message-text").html("User Removed Successfully");
                            $(".fa-fw").attr("class", "fa-fw fa fa-check");
                            $(".alert").show();
                            setMessageTimeout();

                            $.post(url, $('#formConfig').serialize(), function (data, status) {
                                $('#listingData').html(data);
                                hideloading();
                                Reloadables();
                            });

                        },
                        error: function (err) {
                            hideloading();
                            alert(err);
                        }
                    });
                }
            });

            $("#formConfig").on("submit", function () {
                var url = '@Url.Action("AjaxListing")';
                $('#Page').val('1');
                $.post(url, $('#formConfig').serialize(), function (data, status) {
                    $('#listingData').html(data);
                    Reloadables();
                });
                return false;
            });
        }
        $(document).ready(function () {
            Reloadables();
        });
    </script>
}

ThoroughWorks.Web/Views/UserManagement/Listing.cshtml
@using MvcPaging
@using ThoroughWorks.Models
@using ThoroughWorks.Web.Models.Helpers
@model IPagedList<UserDetail_M>


<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th style="width: 20%;">Name</th>
            <th style="width: 15%;" class="hidden-xs hidden-sm">Phone Number</th>
            <th style="width: 30%;" class="hidden-xs">Email</th>
            <th style="width: 15%;" class="hidden-xs">Role</th>
            <th style="width: 15%;"></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count > 0)
        {
            foreach (UserDetail_M user in Model)
            {
            <tr>
                <td>@Html.ActionLink(user.FirstName + " " + user.LastName, "Edit", new { UserID = user.UserID })
                    @Html.HiddenFor(m => user.UserID, new { @class = "user-id"})
                </td>
                <td class="hidden-xs hidden-sm">@user.PhoneNumber </td>
                <td class="hidden-xs">@user.EmailID  </td>
                <td class="hidden-xs">@Html.Raw(user.RoleMasterName)</td>
                <td style="text-align:center;">
                    <a href="@Url.Action("Edit", new { UserID = user.UserID })" class="edit-user btn btn-primary icon-button btn-sm  hidden-xs" title="Edit User"><i class="fa fa-edit"></i></a>
                    <a href="javascript:void(0);" @*onclick="DeleteRecord('@user.UserID')" *@class="remove-user btn btn-danger  icon-button btn-sm" title="Remove User"><i class="fa fa-times"></i></a>
                </td>
            </tr>
            }
        }
    </tbody>
</table>

@if (Model.Count > 0)
{
    @Ajax.CustomAjaxPager(Model.PageSize, Model.PageNumber, Model.TotalItemCount, "AjaxList", null, new CustomAjax
    {
        FormToPost = "#formConfig",
        UrlToPost = @Url.Action("AjaxListing"),
        UpdateType = UpdateType.replace,
        UpdateControl = "#listingData"
    })
}

ThoroughWorks.Web/Views/UserManagement/MyProfile.cshtml
@using ThoroughWorks.Models
@using ThoroughWorks.Web.Models.Helpers
@model UserDetail_M

@{
    ViewBag.Title = "My Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.PageTitle = "My Profile";
    var userFullName = (Model.UserID > 0) ? Model.FirstName + " " + Model.LastName : "User";

    var passwordPlaceholder = "";
    if (Model.UserID > 0)
    {
        passwordPlaceholder = "To change your password please enter here.  Leave blank to keep existing password";
    }
    
}

@section Breadcrumbs
{
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Dashboard")">Home</a>
        </li>
        <li class="active">
            <i class="fa fa-user"></i>
            <a href="@Url.Action("MyProfile", "UserManagement")">
                @Html.Raw("My Profile")
            </a>
        </li>
        <li class="active">
            @userFullName
        </li>
    </ul>
}

<form class="well widget flat radius-bordered no-margin" role="form" method="post" id="formUser">
    <div>
        <div class="widget-header bg-blue">
            <span class="widget-caption">User Information</span>
        </div>
        <div class="widget-body">
            <div class="form-group">
                @Html.LabelFor(m => m.FirstName)
                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.LastName)
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.EmailID)
                @Html.TextBoxFor(m => m.EmailID, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber)
                @Html.TextBoxFor(model => model.PhoneNumber, null, new { maxlength = 20, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
        </div>
        <div class="widget-header bg-blue">
            <span class="widget-caption">Access Details</span>
        </div>
        <div class="widget-body">
            <div class="form-group">
                @Html.LabelFor(model => model.UserName)
                @Html.TextBoxFor(model => model.UserName, new { @class = "form-control", disabled = "disabled" })
                @Html.HiddenFor(model => model.UserName)

                @Html.HiddenFor(model => model.UserID)
                @Html.HiddenFor(model => model.SubscriberID)
            </div>

            <div class="form-group">
                <div>
                    @Html.LabelFor(model => model.RoleMasterIDs)
                    @Html.HiddenFor(model => model.RoleMasterIDs)
                </div>
                @Html.ListBox("SelectedRoles", DropDownHelper.GetAllRoles(Model.RoleMasterIDs, Model.SubscriberID == 0), new { multiple = "multiple", disabled = "disabled", @style = "width:100%;" })
            </div>

        </div>



        <div class="widget-header bg-blue">
            <span class="widget-caption">Email Signature</span>
        </div>
        <div class="widget flat radius-bordered">

            <div class="widget-body">
                <div class="widget-main no-padding">
                    <div id="summernote"></div>
                    @Html.HiddenFor(m => m.EmailSignature)
                </div>
            </div>




            <div class="widget-body">

                <div class="form-group">
                    <button type="submit" class="btn btn-success">Submit</button>
                    <a href="@ViewBag.ReturnUrl" class="btn btn-warning">Cancel</a>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    <script src="~/Scripts/bootstrap-multiselect.js"></script>
    <script src="/content/beyond-admin/js/select2/select2.js"></script>

    <!--Summernote Scripts-->
    <script src="/content/beyond-admin/js/editors/summernote/summernote.js"></script>
    <script>
        $('#summernote').summernote(
            {
                height: 300,
                onImageUpload: function (files, editor, welEditable) {
                    sendFile(files[0], editor, welEditable);

                }
            });

        function sendFile(file, editor, welEditable) {
            data = new FormData();
            data.append("file", file);
            $.ajax({
                data: data,
                type: "POST",
                url: "/UserManagement/SendSignatureImage",
                cache: false,
                contentType: false,
                processData: false,
                success: function (url) {
                    editor.insertImage(welEditable, url);
                }
            })
        };


    </script>


    <script type="text/javascript">

        $(document).ready(function () {
            var sig = $("#EmailSignature").val().replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
            $(".note-editable").html(sig);


            $("#formUser").on("submit", function () {
                $("#EmailSignature").val($(".note-editable").html().replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'));
            });


            // hide video, full screen, code view and help buttons on signature control
            $('button[data-original-title="Video"]').remove();
            $('button[data-original-title="Full Screen"]').remove();
            $('button[data-original-title="Code View"]').remove();
            $('button[data-original-title="Help"]').remove();
            

        });


        jQuery.validator.defaults.ignore = ".ignore";

        $.validator.unobtrusive.parse("#AddEditForm");

        $('.multiselect').multiselect();

        $("#SelectedRoles").select2({
            placeholder: "Select Roles",
            allowClear: true
        });

        

    </script>
}