ThoroughWorks.Web/Controllers/ImageGalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace ThoroughWorks.Web.Controllers
{
    public class ImageGalleryController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult LightBoxPartial()
        {
            return PartialView();
        }
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public FileResult GetImageFile(string imagePath)
        {
            return File(Server.MapPath(imagePath), "image/jpeg");
        }
	}
}

ThoroughWorks.Web/Controllers/SubscriberController.cs
using MvcPaging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThoroughWorks.Data;
using ThoroughWorks.Repository.SubscriberManagement;
using ThoroughWorks.Models;
using ThoroughWorks.Web.Models.Helpers;
using System.IO;

namespace ThoroughWorks.Web.Controllers
{
    [Authorize]
    public class SubscriberController : Controller
    {
        #region "get methods"

        public ActionResult Index()
        {

            IPagedList<Subscriber_M> subscirberm = SelectSubscriberFilterBased(new SubscriberSearch());
            return View(subscirberm);
        }

        [HttpGet]
        public ActionResult Add()
        {
            ViewBag.ReturnUrl = Request.Url.ToString().Replace("Add", "");
            return View("AddEdit", new Subscriber_M());
        }

        [HttpGet]
        public ActionResult Edit(int SubscriberID)
        {
            Subscriber subscriber = SelectSubscriber.SelecSubscriberByID(SubscriberID);

            Subscriber_M subscriber_m = new Subscriber_M()
            {
                Address = subscriber.Address,
                BusinessName = subscriber.BusinessName,
                City = subscriber.City,
                ContactName = subscriber.ContactName,
                EmailID = subscriber.EmailID,
                Fax = subscriber.Fax,
                Mobile = subscriber.Mobile,
                Phone = subscriber.Phone,
                PostalCode = subscriber.PostalCode,
                State = subscriber.State,
                SubscriberID = subscriber.SubscriberID,
                ImagePath = subscriber.LogoFile,
                ResolvedLogoFile = String.IsNullOrEmpty(subscriber.LogoFile) ? "" : Url.Content(subscriber.LogoFile)
            };

            ViewBag.ReturnUrl = Request.Url;

            return View("AddEdit", subscriber_m);
        }

        [HttpGet]
        public ActionResult DeleteRecord(int SubscriberID)
        {
            DeleteSubscriber deletesubscriber = new DeleteSubscriber();
            deletesubscriber.Do(SubscriberID, SessionHelper.UserID);


            IPagedList<Subscriber_M> subscriberPaged = SelectSubscriberFilterBased(new SubscriberSearch());
            return PartialView("Listing", subscriberPaged);
        }

        private IPagedList<Subscriber_M> SelectSubscriberFilterBased(SubscriberSearch search)
        {
            int currentPageIndex = search.Page.HasValue ? search.Page.Value - 1 : 0;
            List<Subscriber> subscribers = (from sub in SelectSubscriber.SelectAllSubscriber()
                                            where (String.IsNullOrWhiteSpace(search.SearchContactName) || Helpers.ConvertString(sub.ContactName).ToLower().Contains(Helpers.ConvertString(search.SearchContactName).ToLower())) &&
                                            (String.IsNullOrWhiteSpace(search.SearchBusinessName) || Helpers.ConvertString(sub.BusinessName).ToLower().Contains(Helpers.ConvertString(search.SearchBusinessName).ToLower()))
                                            select sub).ToList();

            List<Subscriber_M> subscribermodel = (from aa in subscribers
                                                  select new Subscriber_M
                                            {
                                                Address = aa.Address,
                                                BusinessName = aa.BusinessName,
                                                City = aa.City,
                                                ContactName = aa.ContactName,
                                                EmailID = aa.EmailID,
                                                Fax = aa.Fax,
                                                Mobile = aa.Mobile,
                                                Phone = aa.Phone,
                                                PostalCode = aa.PostalCode,
                                                State = aa.State,
                                                ImagePath = aa.LogoFile,
                                                ResolvedLogoFile = String.IsNullOrEmpty(aa.LogoFile) ? "" : Url.Content(aa.LogoFile),
                                                SubscriberID = aa.SubscriberID,
                                                SubscriberPayments = (from payment in aa.SubscriberPayments
                                                                      select new SubscriberPayment_M
                                                                      {
                                                                          SubsciberPaymentID = payment.SubsciberPaymentID,
                                                                          Amount = payment.Amount,
                                                                          DatePaid = payment.DatePaid,
                                                                          ExpirationDate = payment.ExpirationDate
                                                                      }).OrderByDescending(j => j.SubsciberPaymentID).ToList()
                                            }).ToList();
            IPagedList<Subscriber_M> subscriberPaged = subscribermodel.OrderBy(j => j.ContactName).ToPagedList(currentPageIndex, 20);
            return subscriberPaged;
        }

        public ActionResult ShowPayment(int SubscriberID)
        {
            Subscriber_M subscriber_m = SelectPaymentModelByID(SubscriberID);

            return PartialView("PaymentList", subscriber_m);
        }

        private static Subscriber_M SelectPaymentModelByID(int SubscriberID)
        {
            Subscriber subscriber = SelectSubscriber.SelecSubscriberByID(SubscriberID);
            Subscriber_M subscriber_m = new Subscriber_M()
            {
                Address = subscriber.Address,
                BusinessName = subscriber.BusinessName,
                City = subscriber.City,
                ContactName = subscriber.ContactName,
                EmailID = subscriber.EmailID,
                Fax = subscriber.Fax,
                Mobile = subscriber.Mobile,
                Phone = subscriber.Phone,
                PostalCode = subscriber.PostalCode,
                State = subscriber.State,
                ImagePath = subscriber.LogoFile,
                SubscriberID = subscriber.SubscriberID,
                SubscriberPayments = (from payment in subscriber.SubscriberPayments
                                      select new SubscriberPayment_M
                                      {
                                          Amount = payment.Amount,
                                          DatePaid = payment.DatePaid,
                                          ExpirationDate = payment.ExpirationDate,
                                          SubsciberPaymentID = payment.SubsciberPaymentID
                                      }).ToList(),
                SubscriberUsers = (from user in subscriber.SubscriberUsers
                                   select new SubscriberUser_M
                                   {
                                       SubscriberUserID = user.SubscriberUserID,
                                       UserID = user.UserID,
                                       UserName = user.UserDetail.UserName,
                                       RoleNames = user.UserDetail.UserRoles.Count > 0 ? String.Join("<br />", (from bb in user.UserDetail.UserRoles select Convert.ToString(bb.RoleMaster.RoleName)).ToArray()) : "",

                                   }).ToList()
            };
            return subscriber_m;
        }

        public ActionResult DeletePayment(int PaymentID)
        {
            DeleteSubscriber deletesubscriber = new DeleteSubscriber();
            SubscriberPayment payment = deletesubscriber.DeletePayment(PaymentID);

            //get latest payment after deleting
            Subscriber_M subscriber_m = SelectPaymentModelByID(payment.SubscriberID);
            return PartialView("PaymentList", subscriber_m);
        }

        public JsonResult GetPaymentByID(int PaymentID)
        {
            SubscriberPayment payment = SelectSubscriber.SelectSubscriberPaymentByID(PaymentID);

            SubscriberPayment_M model = new SubscriberPayment_M()
            {
                Amount = payment.Amount,
                DatePaid = payment.DatePaid,
                ExpirationDate = payment.ExpirationDate,
                SubsciberPaymentID = payment.SubsciberPaymentID
            };

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ShowUser(int SubscriberID)
        {
            Subscriber_M subscriber_m = SelectPaymentModelByID(SubscriberID);

            return PartialView("UserList", subscriber_m);
        }

        public ActionResult DeleteUser(int SubscriberUserID)
        {
            DeleteSubscriber deletesubscriber = new DeleteSubscriber();
            SubscriberUser user = deletesubscriber.DeleteUser(SubscriberUserID);

            //get latest payment after deleting
            Subscriber_M subscriber_m = SelectPaymentModelByID(user.SubscriberID);
            return PartialView("UserList", subscriber_m);

        }


        #endregion

        #region "Post methods"
        [HttpPost]
        public ActionResult SaveRecord(Subscriber_M subscriber_m, SubscriberSearch search, string ReturnUrl)
        {
            ReturnUrl = String.IsNullOrEmpty(ReturnUrl) ? Request.UrlReferrer.ToString() : ReturnUrl;

            if (ModelState.IsValid) //if valid model then update the record and show list
            {
                Subscriber subscriber = new Subscriber()
                {
                    Address = subscriber_m.Address,
                    BusinessName = subscriber_m.BusinessName,
                    City = subscriber_m.City,
                    ContactName = subscriber_m.ContactName,

ThoroughWorks.Web/Views/Subscriber/AddEdit.cshtml
@using ThoroughWorks.Web.Models.Helpers

@model ThoroughWorks.Models.Subscriber_M

@{
    ViewBag.Title = "Subscriber Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.PageTitle = "Subscriber Details";
}


@section Breadcrumbs
{
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Dashboard")">Home</a>
        </li>
        <li class="active">
            <i class="fa fa-dollar"></i>
            <a href="@Url.Action("Index", "Subscriber")">Subscriptions</a>
        </li>
        <li class="active">
        @if (Model.SubscriberID == 0)
            {
                @Html.Raw("Add New Subsription")
            }
            else
            {
                @Html.Raw("Edit Subsription")
            }
        </li>
    </ul>
}

@*<form class="well widget flat radius-bordered no-margin" role="form" method="post" id="AddEditForm" enctype="multipart/form-data">*@
@using (Html.BeginForm("SaveRecord", "Subscriber", FormMethod.Post, new { @class = "well widget flat radius-bordered no-margin", @enctype = "multipart/form-data" }))
{
    <div>
        <div class="widget-header bg-blue">
            <input id="ReturnUrl" name="ReturnUrl" class="ReturnUrl" type="hidden" value="@ViewBag.ReturnUrl" />
            @Html.HiddenFor(m => m.Active)
            @Html.HiddenFor(m => m.ResolvedLogoFile)
            @if (Model.SubscriberID == 0)
            {
                <span class="widget-caption">New Subscriber</span>
            }
            else
            {
                <span class="widget-caption">Edit @Model.BusinessName</span>
            }
        </div>
        <div class="widget-body">
            <div class="form-group">
                @Html.LabelFor(model => model.ContactName)
                @Html.TextBoxFor(model => model.ContactName, null, new { maxlength = 500, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ContactName)

                @Html.HiddenFor(model => model.SubscriberID, new { @class = "SubscriberID" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BusinessName)
                @Html.TextBoxFor(model => model.BusinessName, null, new { maxlength = 1000, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BusinessName)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EmailID)
                @Html.TextBoxFor(model => model.EmailID, null, new { maxlength = 400, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmailID)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address)
                @Html.TextBoxFor(model => model.Address, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Address)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.City)
                @Html.TextBoxFor(model => model.City, null, new { maxlength = 200, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.City)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.State)
                @Html.TextBoxFor(model => model.State, null, new { maxlength = 200, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.State)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PostalCode)
                @Html.TextBoxFor(model => model.PostalCode, null, new { maxlength = 20, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PostalCode)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Mobile)
                @Html.TextBoxFor(model => model.Mobile, null, new { maxlength = 20, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Mobile)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone)
                @Html.TextBoxFor(model => model.Phone, null, new { maxlength = 20, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Phone)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Fax)
                @Html.TextBoxFor(model => model.Fax, null, new { maxlength = 50, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Fax)
            </div>
        </div>

        <div class="widget-header bg-blue">
            <span class="widget-caption">Logo</span>
        </div>
        @if (!String.IsNullOrWhiteSpace(Model.ImagePath))
        {
            <div class="row no-margin">
                <div class="col-lg-12 col-sm-12">
                    <a href="@Url.Action("GetImageFile", "ImageGallery", new { imagePath = "~/SubscriberFiles/" + Model.SubscriberID + "/" + Model.ImagePath })" target="_blank" title="@Model.BusinessName">
                        <img alt="imgpreview" style="max-width:150px;margin-top:10px" src="@Url.Content("~/SubscriberFiles/" + Model.SubscriberID + "/" + Model.ImagePath)" />
                    </a>
                    <br />
                    <a href="javascript:void(0);" class="removeimage" style="color: red; margin-top: 10px;">Remove Image</a>
                </div>
            </div>
        }
        <div class="widget-body">
             <div class="row no-margin">
            <div class="form-group">
                @Html.LabelFor(model => model.ImagePath)
                @Html.HiddenFor(model => model.ImagePath)
                @Html.EditorFor(model => model.Image)
            </div>
            <div class="col-lg-9 col-sm-9">
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-24">
            @Html.ValidationMessageFor(model => model.Image)
        </div>
        </div>

        <div class="widget-body">
            <div class="form-group">
                @*<button type="button" class="btn btn-success" onclick="SaveRecord();" id="btnSave">Save Changes</button>*@
                <button type="submit" class="btn btn-success">Save Changes</button>

                @if( Helpers.isSuperAdmin() )
                {
                    <a class="btn btn-warning" href="@Url.Action("Index", "Subscriber")">Cancel</a>
                }
            </div>
        </div>
    </div>



}




@section Scripts
{

    <script type="text/javascript">
        $(document).ready(function () {
            $(".removeimage").on("click", function () {
                var subID = '@Model.SubscriberID';
                if (confirm("Are you sure you want to remove this image?")) {
                    $.post("/Subscriber/RemoveImage", { id: subID }, function (data) {
                        location.href = $("#ReturnUrl").val();
                    });
                }
            });
        });
    </script>
}

ThoroughWorks.Web/Views/Subscriber/Index.cshtml
@model MvcPaging.IPagedList<ThoroughWorks.Models.Subscriber_M>

@{
    ViewBag.Title = "Subscriber Management";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.PageTitle = "Subscriber Management";
}


@section Breadcrumbs
{
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Dashboard")">Home</a>
        </li>
        <li class="active">
            <i class="fa fa-dollar"></i>
            Subscriptions
        </li>
    </ul>
}

<div id="divlist">
    <div class="row">
        <div class="col-lg-4 col-sm-4 col-xs-8">
            <a class="btn btn-blue" href="@Url.Action("Add", "Subscriber")";" >Add a New Subscriber</a>
        </div>
    </div>
    <div class="well">
        <form id="formConfig" name="formConfig">
            <h4>Search</h4>
            <input type="hidden" id="Page" name="page" />
            <div class="form-inline">
                <div class="form-group ">
                    <div class="col-lg-12 no-padding">
                        <label class="sr-only" for="SearchContactName">Contact Name</label>
                        @Html.TextBox("SearchContactName", "", new { @class = "form-control", placeholder = "Contact Name" })
                    </div>
                </div>
                <div class="form-group ">
                    <div class="col-lg-12 no-padding">
                        <label class="sr-only" for="SearchBusinessName">Business Name</label>
                        @Html.TextBox("SearchBusinessName", "", new { @class = "form-control", placeholder = "Business Name" })
                    </div>
                </div>
                <div class="form-group ">
                    <div class="col-lg-12 no-padding">
                        <input type="submit" class="btn btn-blue" value="Search">
                    </div>
                </div>
            </div>
        </form>
        <div class="clear"></div>
    </div>
    <div id="listingData">
        @{Html.RenderPartial("Listing", Model);}
    </div>
</div>

<div id="PaymentList">
</div>

<div id="UserList">
</div>


@section Scripts
{
    <link href="~/Content/dropzone.css" rel="stylesheet" />
    <script src="~/Scripts/dropzone.js"></script>
    <script src="~/Scripts/bootstrap-multiselect.js"></script>
    <script src="~/Content/beyond-admin/js/datetime/bootstrap-datepicker.js"></script>
    <script type="text/javascript">
 

        function SearchRecord() {
            var url = '@Url.Action("AjaxListing")';
            $('#Page').val('1');
            $.post(url, $('#formConfig').serialize(), function (data, status) {
                $('#listingData').html(data);
            });
            return false;
        }

        
    </script>


}

ThoroughWorks.Web/Views/Subscriber/PaymentList.cshtml
@using ThoroughWorks.Models
@using ThoroughWorks.Web.Models.Helpers
@model Subscriber_M

<div class="well widget flat radius-bordered no-margin">
    <div>
        <div class="widget-header bg-blue">
            <span class="widget-caption">@Model.ContactName - Payment History</span>
        </div>
        <div class="widget-body">
            <div class="form-group">
                <button type="button" class="btn btn-default" onclick="BackToSubscriber();">Back</button>
            </div>
            <div class="form-group">

                <form id="frmPayment">
                    <table class="table table-striped table-hover table-bordered">
                        <thead>
                            <tr>
                                <th style="width: 23%;">Amount</th>
                                <th style="width: 23%;">Date Paid</th>
                                <th style="width: 23%;">Expiration Date</th>
                                <th style="width: 30%"></th>
                            </tr>
                        </thead>
                        <tbody>

                            @if (Model.SubscriberPayments.Count > 0)
                            {
                                foreach (SubscriberPayment_M payment in Model.SubscriberPayments)
                                {
                                <tr>
                                    <td>@payment.Amount.ToString("N2")  </td>
                                    <td>@Helpers.ConvertDateToString(payment.DatePaid)  </td>
                                    <td>@Helpers.ConvertDateToString(payment.ExpirationDate) </td>
                                    <td>
                                        <a href="javascript:void(0);" onclick="EditPayment('@payment.SubsciberPaymentID');" class="edit-user btn btn-primary icon-button btn-sm  hidden-xs" title="Edit Payment"><i class="fa fa-edit"></i></a>
                                        <a href="javascript:void(0);" onclick="DeletePayment('@payment.SubsciberPaymentID')" class="remove-user btn btn-danger  icon-button btn-sm" title="Remove Payment"><i class="fa fa-times"></i></a>
                                </tr>
                                }
                            }

                            <tr>
                                <td>
                                    <input type="text" name="Amount" value="" onkeypress="return onlyPositiveNumbersWithDecimal(this,event);" class="form-control" />
                                    @Html.ValidationMessage("Amount")

                                    @Html.HiddenFor(j => j.SubscriberID)
                                    @Html.Hidden("SubsciberPaymentID", "")
                                </td>
                                <td>
                                    <input type="text" name="DatePaid" value="" class="form-control date-picker" data-date-format="dd/mm/yyyy" />
                                    @Html.ValidationMessage("DatePaid")
                                </td>
                                <td>
                                    <input type="text" name="ExpirationDate" value="" class="form-control date-picker" data-date-format="dd/mm/yyyy" />
                                    @Html.ValidationMessage("ExpirationDate")
                                </td>
                                <td>
                                    <input type="submit" class="btn btn-success" id="SaveUpdate" value="Add" onclick="return AddPayment();">
                                    <input type="button" class="btn btn-default" id="Cancel" value="Cancel" onclick="return CancelPayment();">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    initPlugins();
    //$('.date-picker').datepicker({ dateFormat: 'dd/mm/yy' });

    function DeletePayment(id) {
        if (confirm('Are you sure you want to delete this record?')) {
            getRequest('@Url.Action("DeletePayment")' + '?PaymentID=' + id, '#PaymentList');
        }

    }
    function BackToSubscriber() {

        var url = '@Url.Action("AjaxListing")';
        $.post(url, $('#formConfig').serialize(), function (data, status) {
            $('#listingData').html(data);
            $('#PaymentList').hide();
            $('#divlist').show();
            $('#AddEditScreen').hide();
            $('#UserList').hide();
        });


    }

    function EditPayment(id) {
        var url = '@Url.Action("GetPaymentByID", "Subscriber")' + '?PaymentID=' + id
        $.getJSON(url, null, function (data) {
            $("[name='Amount']").val(data.Amount);
            $("[name='DatePaid']").val(data.DatePaidStr);
            $("[name='ExpirationDate']").val(data.ExpirationDateStr);
            $("[name='SubsciberPaymentID']").val(data.SubsciberPaymentID);
            $('#SaveUpdate').val('Update');
        });
    }

    function CancelPayment() {
        $("[name='Amount']").val('');
        $("[name='DatePaid']").val('');
        $("[name='ExpirationDate']").val('');
        $("[name='SubsciberPaymentID']").val('');
        $('#SaveUpdate').val('Add');
        return false;
    }
    function AddPayment() {
        if (Valid() == true) {

            showloading();
            var url = '@Url.Action("SavePayment")';
                $.post(url, $('#frmPayment').serialize(), function (data, status) {
                    $('#PaymentList').html(data);

                    hideloading();
                }).error(function (error, status, a, b) {
                    $('#PaymentList').html(error.responseText);
                    hideloading();
                });

            }
            return false;
        }
        function Valid() {
            var bvalid = true;
            if ($.trim($("[name='Amount']").val()) == '') {
                $("[name='Amount']").css('border', '1px solid red');
                bvalid = false;
            }
            else {
                $("[name='Amount']").css('border', '');
            }

            if ($.trim($("[name='DatePaid']").val()) == '') {
                $("[name='DatePaid']").css('border', '1px solid red');
                bvalid = false;
            }
            else {
                $("[name='DatePaid']").css('border', '');
            }


            if ($.trim($("[name='ExpirationDate']").val()) == '') {
                $("[name='ExpirationDate']").css('border', '1px solid red');
                bvalid = false;
            }
            else {
                $("[name='ExpirationDate']").css('border', '');
            }

            return bvalid;
        }
</script>